### PR TITLE
Allow usage of pokemon id instead of name

### PR DESCRIPTION
**Pull request by 123FLO321**
This PR allows users to use the pokemons id inside commands.
e.g. `!addpokemon 201`

ohne titel 999

### CODE REVIEW

**Comment by novskey** [comment]
Does it work with iv? Eg how do I add Pokémon 129 with min iv of 100?

**Comment by 123FLO321** [comment]
You’re right. Thats a problem.  Would it be save to assume that pokemon can only be specific in the first param? So first always pokemon else iv?

**Comment by novskey** [comment]
Not necessarily. I used to have it like that, but now the parser is order independent (apart from the command coming first). One option would be to make it so iv requires to be entered like 100iv or iv100, similar to cp and level. Might confuse people tho. Other option is to add a new special way to add Pokémon by id maybe poke201 or something?

**Comment by 123FLO321** [comment]
now requires `p` `pid` `poke` or `pokemon` in front:
e.g.: `!addpokemon p201 100`

**Comment by novskey** [comment]
Looking good mate, have you tested it? Almost midnight now but will merge tomorrow if all looks good, thanks heaps!

**Comment by 123FLO321** [comment]
@novskey I been running this together with #24 and it's working without a problem so far.

**Pull request merged**
